<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Gmmt.Patch</RootNamespace>
    <AssemblyName>Gmmt.Patch</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Gmmt.Core\Gmmt.Core.csproj" />
    <ProjectReference Include="..\Gmmt.Diff\Gmmt.Diff.csproj" />
  </ItemGroup>

</Project>
